### ISSUE TITLE
Error with resolving 'Crypto' Module while Trying to Run React Native Drizzle Tutorial

### ISSUE THREAD

**Issue by francolynn** [trufflesuite/trufflesuite.com#354]
I am having issues running the DrizzleReactNativeTutorial app while following instructions given at https://truffleframework.com/tutorials/drizzle-and-react-native. When I attempt to run the app on my android emulator, I receive the error message below. I understand that the crypto module is no longer supported, however, the workaround provided by the "rn-cli.config.js" and "shims.js" files doesn't seem to be working either. Can anyone suggest changes that I need to make or a different workaround?

> `error: bundling failed: Error: While trying to resolve module `crypto` from file `/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/eth-lib/lib/bytes.js`, the package `/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/crypto/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/crypto/index.js`. Indeed, none of these files exist:

  * `/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/crypto/index.js(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
  * `/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/crypto/index.js/index(.native||.android.js|.native.js|.js|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)`
    at ResolutionRequest.resolveDependency (/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:65:15)
    at DependencyGraph.resolveDependency (/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/metro/src/node-haste/DependencyGraph.js:283:16)
    at Object.resolve (/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/metro/src/lib/transformHelpers.js:261:42)
    at dependencies.map.result (/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/metro/src/DeltaBundler/traverseDependencies.js:399:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/metro/src/DeltaBundler/traverseDependencies.js:396:18)
    at /Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/metro/src/DeltaBundler/traverseDependencies.js:269:33
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/metro/src/DeltaBundler/traverseDependencies.js:87:24)
    at _next (/Users/admin/TandaPay/DrizzleReactNativeTutorial/node_modules/metro/src/DeltaBundler/traverseDependencies.js:107:9)
 DELTA  [android, dev] ./index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.`

**Comment by CruzMolina** [comment]
CC @honestbonsai @cds-amal

**Comment by francolynn** [comment]
Okay, I figured it out.

1. The code for **rn-cli.config.js** should go in **metro.config.js**
2. In **shims.js** on Line 2: the brackets around **btoa** need to be removed.

**Comment by DiscRiskandBisque** [comment]
Hi @francolynn! Thanks for investigating this and sorry for the late response. Could you open a PR with these changes? If you don't have time let me know and we'll implement--thanks!

**Comment by DiscRiskandBisque** [comment]
Closing because we have since deprecated this tutorial.
