### ISSUE TITLE
debugging-a-smart-contract.md - debugging doesn't work

### ISSUE THREAD

**Issue by 7--** [trufflesuite/trufflesuite.com#602]
I followed the guide step by step but when you get to the first debugging part it gives this error:
```
truffle(develop)> SimpleStorage.deployed().then(function(instance){return instance.set(4);});
{ tx:
   '0x4c42c692f02dfa01c0cc4081d9f4edff5e19c6e0cde985d4fa8aed61e01ce5e8',
  receipt:
   { transactionHash:
      '0x4c42c692f02dfa01c0cc4081d9f4edff5e19c6e0cde985d4fa8aed61e01ce5e8',
     transactionIndex: 0,
     blockHash:
      '0x420181dfce48c69734a02275439496f3790a01244b5574a5b24d2ae4abfb575b',
     blockNumber: 1,
     from: '0xadf0476d8ec017499308c2e57713ede907282303',
     to: '0x5d2daf2a1857b228e6151ff2d9794b637bd28f4c',
     gasUsed: 21204,
     cumulativeGasUsed: 21204,
     contractAddress: null,
     logs: [],
     status: true,
     logsBloom:
      '0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000',
     v: '0x25',
     r:
      '0x9720e64ea2cb54e9bf6077704c9094f2b9d0873a74402fef0be138d31e0ed4bb',
     s:
      '0x2164bedd4cd5e99fe5ca8f65eb9549b516102c05e8fe6d2dde5de75a028d1623',
     rawLogs: [] },
  logs: [] }
truffle(develop)> debug 0x4c42c692f02dfa01c0cc4081d9f4edff5e19c6e0cde985d4fa8aed61e01ce5e8
Starting Truffle Debugger...
✔ Compiling your contracts...
⠙ Gathering information about your project and the transaction...{ Error: Cannot find module "."
    at webpackMissingModule (/usr/local/lib/node_modules/truffle/build/webpack:/packages/debugger/node_modules/semver/index.js:3:52)
    at lazyRequire (/usr/local/lib/node_modules/truffle/build/webpack:/packages/debugger/node_modules/semver/index.js:3:52)
    at Object.get [as satisfies] (/usr/local/lib/node_modules/truffle/build/webpack:/packages/debugger/node_modules/semver/index.js:10:1)
    at contextRequiresPhantomStackframes (/usr/local/lib/node_modules/truffle/build/webpack:/packages/debugger/dist/debugger.js:1015:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/reselect/es/index.js:70:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/reselect/es/index.js:30:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/reselect/es/index.js:84:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/reselect/es/index.js:30:1
    at runSelectEffect (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:730:1)
    at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1204:1)
    at digestEffect (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1271:1)
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1161:1)
    at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1251:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:481:1
    at exec (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:31:1)
    at flush (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:87:1)
    at asap (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:46:1)
    at runPutEffect (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:468:1)
    at runEffect (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1204:1)
    at digestEffect (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1271:1)
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1161:1)
    at currCb (/usr/local/lib/node_modules/truffle/build/webpack:/node_modules/@redux-saga/core/dist/redux-saga-core.esm.js:1251:1) code: 'MODULE_NOT_FOUND' }
The above error occurred in task session.saga
Tasks cancelled due to error:
listenerSaga
controller.saga
data.saga
evm.saga
solidity.saga
trace.saga
web3.saga
truffle(develop)> debug 0x4c42c692f02dfa01c0cc4081d9f4edff5e19c6e0cde985d4fa8aed61e01ce5e8Error: Cannot find module "."Error: Cannot find modul⠴ Gathering information about your project and the transaction...
```

**Comment by haltman-at** [comment]
Hello!  Sorry about that.  Fortunately, I've already written a [fix](https://github.com/trufflesuite/truffle/pull/2777) for this issue that will go out in the next release, which should be tomorrow.  Once the new version is out, try upgrading and see if that fixes it!

(Btw, this isn't really the right repo to post this issue on -- this is the repo for the Truffle website, not for Truffle itself.  You're looking for [the Truffle repo](https://github.com/trufflesuite/truffle).)

**Comment by 7--** [comment]
Thank you for letting me know
