### ISSUE TITLE
Contract: MetaCoin should send coin correctly:      Error: Invalid number of arguments to Solidity function

### ISSUE THREAD

**Issue by plash29** [trufflesuite/trufflesuite.com#64]
$ truffle test
Using network 'development'.

Compiling .\contracts\ConvertLib.sol...
Compiling .\contracts\MetaCoin.sol...
Compiling .\test\TestMetacoin.sol...
Compiling truffle/Assert.sol...
Compiling truffle/DeployedAddresses.sol...

Compilation warnings encountered:

/E/webpack/test/TestMetacoin.sol:9:3: Warning: No visibility specified. Defaulting to "public".
  function testInitialBalanceUsingDeployedContract() {
  ^
Spanning multiple lines.
,/E/webpack/test/TestMetacoin.sol:17:3: Warning: No visibility specified. Defaulting to "public".
  function testInitialBalanceWithNewMetaCoin() {
  ^
Spanning multiple lines.

  TestMetacoin
    √ testInitialBalanceUsingDeployedContract (56ms)
    √ testInitialBalanceWithNewMetaCoin (54ms)

  Contract: MetaCoin
    √ should put 10000 MetaCoin in the first account
    √ should call a function that depends on a linked library
    1) should send coin correctly
    > No events were emitted

  4 passing (1s)
  1 failing

  1) Contract: MetaCoin should send coin correctly:
     Error: Invalid number of arguments to Solidity function
      at Object.InvalidNumberOfSolidityArgs (C:\Users\pankaj.thakur\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:41471:16)
      at SolidityFunction.validateArgs (C:\Users\pankaj.thakur\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:327892:22)
      at SolidityFunction.toPayload (C:\Users\pankaj.thakur\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:327908:10)
      at SolidityFunction.call (C:\Users\pankaj.thakur\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:327949:24)
      at C:\Users\pankaj.thakur\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:316821:16
      at new Promise (<anonymous>)
      at C:\Users\pankaj.thakur\AppData\Roaming\npm\node_modules\truffle\build\cli.bundled.js:316812:18
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)

**Comment by bmmpxf** [comment]
Hi @plash29 . Sorry you're having issues. MetaCoin is used in a few different places. Can you tell us what specific Truffle Box you were using or what tutorial you were following?

**Comment by DiscRiskandBisque** [comment]
Closing this due to age, but please re-open if you haven't found a solution.
