### ISSUE TITLE
how to get account public key in test case?

### ISSUE THREAD

**Issue by qiluge** [trufflesuite/trufflesuite.com#738]
I write some simple code:
```
var Wallet = require("ethereumjs-wallet");

contract('DidUtils', (accounts) => {
    console.log(accounts[0].privateKey);
    const acc = Wallet.fromPrivateKey(accounts[0].privateKey);
    console.log(acc.getPublicKeyString());
});
```
And the I run the `test tests/TestDIDUtils.js` in truffle develop console, but the output is, it seems there are no `privateKey` in account object:
```
> Everything is up to date, there is nothing to compile.

undefined
TypeError: Wallet.fromPrivateKey is not a function
    at /mnt/g/js workdspace/eth-contract/UID-discovery-solidity/tests/TestDIDUtils.js:8:24
    at Suite.template (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:344:1)
    at Suite.<anonymous> (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:349:1)
    at Object.create (/home/qiluge/nodejs/lib/node_modules/truffle/node_modules/mocha/lib/interfaces/common.js:143:19)
    at Function.context.describe.context.context (/home/qiluge/nodejs/lib/node_modules/truffle/node_modules/mocha/lib/interfaces/bdd.js:42:27)
    at global.contract (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:348:1)
    at Object.<anonymous> (/mnt/g/js workdspace/eth-contract/UID-discovery-solidity/tests/TestDIDUtils.js:5:1)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at /home/qiluge/nodejs/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:384:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/qiluge/nodejs/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:381:14)
    at Mocha.run (/home/qiluge/nodejs/lib/node_modules/truffle/node_modules/mocha/lib/mocha.js:954:10)
    at /home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:159:1
    at new Promise (<anonymous>)
    at Object.run (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/packages/core/lib/test.js:158:1)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
And when I log account in truffle develop console, the output also be undefined:
```
truffle(develop)> let accounts = web3.eth.getAccounts()
undefined
truffle(develop)> accounts[0]
undefined
truffle(develop)> web3.eth.sign("000", accounts[0])
/home/qiluge/nodejs/lib/node_modules/truffle/build/cli.bundled.js:212086
throw new Error('Provided address "'+ address +'" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can\'t be c
onverted.');
^

Uncaught:
Error: Provided address "undefined" is invalid, the capitalization checksum test failed, or its an indrect IBAN address which can't be converted.
at Method.inputAddressFormatter (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-helpers/src/formatters.js:409:1)
at /home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-method/src/index.js:144:1
at Array.map (<anonymous>)
at Method.formatInput (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-method/src/index.js:142:1)
at Method.toPayload (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-method/src/index.js:177:1)
at Eth.send (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/node_modules/web3-core-method/src/index.js:467:1)
at evalmachine.<anonymous>:0:10
at sigintHandlersWrap (vm.js:274:15)
at Script.runInContext (vm.js:128:14)
at runScript (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:222:1)
at Console.interpret (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/packages/core/lib/console.js:237:1)
at ReplManager.interpret (/home/qiluge/nodejs/lib/node_modules/truffle/build/webpack:/packages/core/lib/repl.js:129:1)
at bound (domain.js:426:14)
at REPLServer.runBound [as eval] (domain.js:439:12)
at REPLServer.onLine (repl.js:760:10)
at REPLServer.emit (events.js:315:20)
at REPLServer.EventEmitter.emit (domain.js:482:12)
at REPLServer.Interface._onLine (readline.js:329:10)
at REPLServer.Interface._line (readline.js:658:8)
at REPLServer.Interface._ttyWrite (readline.js:999:14)
at REPLServer.self._ttyWrite (repl.js:851:9)
at ReadStream.onkeypress (readline.js:205:10)
```
I cannot sign some data in console neither.

**Comment by bellaj** [comment]
Same here, any potential directions?
